import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
// Design system: "Kinetic Command" (Google Stitch project 2394034031028131565).
// Palette / fonts / radius ported verbatim from the Stitch tailwind.config so the
// utility classes copied out of each screen render identically.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "ai-processing": "#8b5cf6",
        background: "#f7f9fb",
        "draft-gray": "#64748b",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "failed-error": "#ef4444",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#c6c6c6",
        "inverse-surface": "#2d3133",
        "on-background": "#191c1e",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#848484",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fefcff",
        "on-secondary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#004395",
        "on-surface": "#191c1e",
        "on-surface-variant": "#4c4546",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#848484",
        "on-tertiary-fixed": "#1b1b1b",
        "on-tertiary-fixed-variant": "#474747",
        outline: "#7e7576",
        "outline-variant": "#cfc4c5",
        primary: "#000000",
        "primary-container": "#1b1b1b",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        secondary: "#0058be",
        "secondary-container": "#2170e4",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#adc6ff",
        "success-published": "#10b981",
        surface: "#f7f9fb",
        "surface-border": "#e2e8f0",
        "surface-bright": "#f7f9fb",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d8dadc",
        "surface-tint": "#5e5e5e",
        "surface-variant": "#e0e3e5",
        tertiary: "#000000",
        "tertiary-container": "#1b1b1b",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c6",
        "warning-review": "#f59e0b",
      },
      fontFamily: {
        // Ported verbatim from the Stitch config so `font-*` classes resolve.
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        // Base aliases used by index.css.
        display: ["Hanken Grotesk", "sans-serif"],
        headline: ["Hanken Grotesk", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      spacing: {
        "margin-mobile": "16px",
        base: "4px",
        gutter: "24px",
        "margin-desktop": "40px",
        "container-max": "1440px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [forms],
};
